# Task 1: Data Cleaning and Preprocessing

## Dataset: Customer Personality Analysis

### Intership: DataX Labs - Data Analyst Internship

### Objective

Clean and prepare a raw dataset by handling missing values, removing duplicates, standardizing text, fixing data types, and engineering new features...

### Tools Used 

- Python (Pandas, Numpy)
- Jupyter Notebook (VS Code)

### Dataset Source 

[Customer Personality Analysis - Kaggle](https://www.kaggle.com/datasets/imakash3011/customer-personality-analysis)

### Dataset Overview

- **Rows:** 2240
- **Columns:** 29
- **Key Issues Found:** Missing values in Income, inconsistent Marital_Status values, wrong data types, constant columns

In [2]:
# Import libraries
import pandas as pd
import numpy as np

In [3]:
# Load dataset
df=pd.read_csv("customer_personality_analysis.csv")

In [9]:
# data inspection
# first 5 rows of the dataset
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [8]:
#basic information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   str
 3   Marital_Status       2240 non-null   str
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   str
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), str(3)
memory usage: 507.6 KB

In [7]:
#statistical summary of the dataset
df.describe()

,ID,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000
mean,5592.159821,1968.805804,52247.251354,0.444196,0.506250,49.109375,303.935714,26.302232,166.950000,37.525446,...,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107
std,3246.662198,11.984069,25173.076661,0.538398,0.544538,28.962453,336.597393,39.773434,225.715373,54.628979,...,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000

In [10]:
# cloumn names of the dataset
df.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='str')

In [11]:
# checking for missing values
df.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [12]:
# 'income' column has 24 missing values in this dataset... so we are filling with median (for better than mean for skewed data)
df['Income'].fillna(df['Income'].median(), inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_30260\1922672427.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Income'].fillna(df['Income'].median(), inplace=True)

0       58138.0
1       46344.0
2       71613.0
3       26646.0
4       58293.0
         ...
2235    61223.0
2236    64014.0
2237    56981.0
2238    69245.0
2239    52869.0
Name: Income, Length: 2240, dtype: float64

In [13]:
# verifying if the missing values are filled
print(df.isnull().sum())

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [14]:
# remove duplicates
print("Before:", df.shape)

df.drop_duplicates(inplace=True)

print("After:", df.shape)

Before: (2240, 29)
After: (2240, 29)

In [15]:
# fixing data types
# converting 'Dt_Customer' column to datetime format
df['Dt_Customer']=pd.to_datetime(df['Dt_Customer'], dayfirst=True)

#verifying the data type of 'Dt_Customer' column
print(df['Dt_Customer'].dtype)

datetime64[us]

In [25]:
print(df['Marital_Status'].unique())

<StringArray>
['Single', 'Together', 'Married', 'Divorced', 'Widow', 'Alone', 'Absurd',
 'Yolo']
Length: 8, dtype: str

In [26]:
# Fix inconsistent Marital_Status values
df['Marital_Status']=df['Marital_Status'].replace({
    'Alone': 'Single',
    'Absurd': 'Single',
    'YOLO': 'Single'
})

print(df['Marital_Status'].unique())

<StringArray>
['Single', 'Together', 'Married', 'Divorced', 'Widow', 'Yolo']
Length: 6, dtype: str

In [17]:
# standardize text column 
df["Education"]=df["Education"].str.strip().str.title()

df["Marital_Status"]=df["Marital_Status"].str.strip().str.title()

In [18]:
# create age column 
current_year=2026

df['age']=current_year-df['Year_Birth']

In [19]:
df[['Year_Birth','age']].head()

   Year_Birth  age
0        1957   69
1        1954   72
2        1965   61
3        1984   42
4        1981   45

In [20]:
# check data types

df.dtypes

ID                              int64
Year_Birth                      int64
Education                         str
Marital_Status                    str
Income                        float64
Kidhome                         int64
Teenhome                        int64
Dt_Customer            datetime64[us]
Recency                         int64
MntWines                        int64
MntFruits                       int64
MntMeatProducts                 int64
MntFishProducts                 int64
MntSweetProducts                int64
MntGoldProds                    int64
NumDealsPurchases               int64
NumWebPurchases                 int64
NumCatalogPurchases             int64
NumStorePurchases               int64
NumWebVisitsMonth               int64
AcceptedCmp3                    int64
AcceptedCmp4                    int64
AcceptedCmp5                    int64
AcceptedCmp1                    int64
AcceptedCmp2                    int64
Complain                        int64
Z_CostContact                   int64
Z_Revenue                       int64
Response                        int64
age                             int64
dtype: object

In [21]:
# drop unnecessary columns: 
df.drop(['Z_CostContact','Z_Revenue'], axis=1, inplace=True) # this constant columns -no analytical value

In [22]:
# save the cleaned dataset to a new CSV file
df.to_csv("customer_cleaned_data.csv", index=False)

print("Cleaned Dataset Saved!")

Cleaned Dataset Saved!

In [24]:
# ============================================================
#            FINAL SUMMARY — DATA CLEANING REPORT
# ============================================================

print("=" * 60)
print("       TASK 1: DATA CLEANING AND PREPROCESSING")
print("       Dataset: Customer Personality Analysis")
print("=" * 60)

print(f"""
    ORIGINAL DATASET:
   • Total Rows     : 2240
   • Total Columns  : 29

     CLEANING STEPS PERFORMED:
   1. Loaded dataset (comma-separated)
   2. Inspected shape, dtypes, and missing values
   3. Filled 24 missing 'Income' values with median
   4. Removed duplicate rows (0 found — dataset was clean)
   5. Converted 'Dt_Customer' to datetime format
   6. Standardized 'Education' and 'Marital_Status' (title case)
   7. Created new 'Age' column from 'Year_Birth' (current year: 2026)
   8. Dropped constant columns: Z_CostContact, Z_Revenue
   9. Saved cleaned dataset as 'customer_cleaned_data.csv'

     FINAL CLEANED DATASET:
   • Total Rows     : {df.shape[0]}
   • Total Columns  : {df.shape[1]}

     Dataset is now clean and ready for analysis!
""")

print("=" * 60)
print("           Completed by: Ayesha Muskan A")
print("           Internship  : DataX Labs")
print("           Tool        : Python (Pandas) | Jupyter Notebook")
print("=" * 60)

============================================================
       TASK 1: DATA CLEANING AND PREPROCESSING
       Dataset: Customer Personality Analysis
============================================================

    ORIGINAL DATASET:
   • Total Rows     : 2240
   • Total Columns  : 29

     CLEANING STEPS PERFORMED:
   1. Loaded dataset (comma-separated)
   2. Inspected shape, dtypes, and missing values
   3. Filled 24 missing 'Income' values with median
   4. Removed duplicate rows (0 found — dataset was clean)
   5. Converted 'Dt_Customer' to datetime format
   6. Standardized 'Education' and 'Marital_Status' (title case)
   7. Created new 'Age' column from 'Year_Birth' (current year: 2026)
   8. Dropped constant columns: Z_CostContact, Z_Revenue
   9. Saved cleaned dataset as 'customer_cleaned_data.csv'

     FINAL CLEANED DATASET:
   • Total Rows     : 2240
   • Total Columns  : 28

     Dataset is now clean and ready for analysis!

============================================================
           Completed by: Ayesha Muskan A
           Internship  : DataX Labs
           Tool        : Python (Pandas) | Jupyter Notebook
============================================================